const webpack = require('webpack');

// Webpack plugins
const CompressionPlugin = require('compression-webpack-plugin');

module.exports = env => ({
  // Configures how source maps should be created
  devtool: 'none',

  // Configure's destination for the bundled code
  output: {
    filename: './js/[name].[chunkHash:8].js'
  },

  optimization: {
    // Configure's how the final transpiled javascript should be split into
    // multiple files.
    // This config will create 2 separate javascript files, one for our code
    // and the other for code from node modules.
    // When our app starts growing large we can in turn split node modules
    // into multiple javascript files
    splitChunks: {
      chunks: 'all',
      name: 'vendor'
    },
  },

  // Configure's additions plugins to be used by webpack
  // Order of plugins is important
  plugins: [
    // Handles file hashes so that they don't change unexpectedly
    new webpack.HashedModuleIdsPlugin(),

    // Gzip's all assets (js, css, images etc.) generated by webpack
    new CompressionPlugin(),
  ]
});